name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: docker build . --tag ghcr.io/${{ github.actor }}/hello:latest
        
      - name: run image
        run: docker run ghcr.io/${{ github.actor }}/hello:latest 

      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.actor }}/hello:latest